import type { Hison } from 'hisonjs';
import type { HisonConfig } from '../types'

export const setHisonFromHisonConfig = (hison: Hison, hisonConfig: HisonConfig) => {
    //utils
    if(hisonConfig.dateFormat !== undefined && hisonConfig.dateFormat !== null) hison.setDateFormat(hisonConfig.dateFormat)
    if(hisonConfig.timeFormat !== undefined && hisonConfig.timeFormat !== null) hison.setTimeFormat(hisonConfig.timeFormat)
    if(hisonConfig.datetimeFormat !== undefined && hisonConfig.datetimeFormat !== null) hison.setDatetimeFormat(hisonConfig.datetimeFormat)
    if(hisonConfig.yearFormat !== undefined && hisonConfig.yearFormat !== null) hison.setYearFormat(hisonConfig.yearFormat)
    if(hisonConfig.monthFormat !== undefined && hisonConfig.monthFormat !== null) hison.setMonthFormat(hisonConfig.monthFormat)
    if(hisonConfig.yearMonthFormat !== undefined && hisonConfig.yearMonthFormat !== null) hison.setYearMonthFormat(hisonConfig.yearMonthFormat)
    if(hisonConfig.dayFormat !== undefined && hisonConfig.dayFormat !== null) hison.setDayFormat(hisonConfig.dayFormat)
    if(hisonConfig.dayOfWeekFormat !== undefined && hisonConfig.dayOfWeekFormat !== null) hison.setDayOfWeekFormat(hisonConfig.dayOfWeekFormat)
    if(hisonConfig.hourFormat !== undefined && hisonConfig.hourFormat !== null) hison.setHourFormat(hisonConfig.hourFormat)
    if(hisonConfig.hourMinuteFormat !== undefined && hisonConfig.hourMinuteFormat !== null) hison.setHourMinuteFormat(hisonConfig.hourMinuteFormat)
    if(hisonConfig.minuteFormat !== undefined && hisonConfig.minuteFormat !== null) hison.setMinuteFormat(hisonConfig.minuteFormat)
    if(hisonConfig.secondFormat !== undefined && hisonConfig.secondFormat !== null) hison.setSecondFormat(hisonConfig.secondFormat)
    if(hisonConfig.numberFormat !== undefined && hisonConfig.numberFormat !== null) hison.setNumberFormat(hisonConfig.numberFormat)
    if(hisonConfig.LESSOREQ_0X7FF_BYTE !== undefined && hisonConfig.LESSOREQ_0X7FF_BYTE !== null) hison.setCharByteLess2047(hisonConfig.LESSOREQ_0X7FF_BYTE)
    if(hisonConfig.LESSOREQ_0XFFFF_BYTE !== undefined && hisonConfig.LESSOREQ_0XFFFF_BYTE !== null) hison.setCharByteLess65535(hisonConfig.LESSOREQ_0XFFFF_BYTE)
    if(hisonConfig.GREATER_0XFFFF_BYTE !== undefined && hisonConfig.GREATER_0XFFFF_BYTE !== null) hison.setCharByteGreater65535(hisonConfig.GREATER_0XFFFF_BYTE)
    //shield
    if(hisonConfig.shieldURL !== undefined && hisonConfig.shieldURL !== null) hison.setShieldURL(hisonConfig.shieldURL)
    if(hisonConfig.exposeIpList !== undefined && hisonConfig.exposeIpList !== null) hison.setExposeIpList(hisonConfig.exposeIpList)
    if(hisonConfig.isFreeze !== undefined && hisonConfig.isFreeze !== null) hison.setIsFreeze(hisonConfig.isFreeze)
    if(hisonConfig.isPossibleGoBack !== undefined && hisonConfig.isPossibleGoBack !== null) hison.setIsPossibleGoBack(hisonConfig.isPossibleGoBack)
    if(hisonConfig.isPossibleOpenDevTool !== undefined && hisonConfig.isPossibleOpenDevTool !== null) hison.setIsPossibleOpenDevTool(hisonConfig.isPossibleOpenDevTool)
    if(hisonConfig.doDetectDevTool !== undefined && hisonConfig.doDetectDevTool !== null) hison.setDoDetectDevTool(hisonConfig.doDetectDevTool)
    //data
    if(hisonConfig.convertValue !== undefined && hisonConfig.convertValue !== null) hison.setConvertValue(hisonConfig.convertValue)
    //link
    if(hisonConfig.protocol !== undefined && hisonConfig.protocol !== null) hison.setProtocol(hisonConfig.protocol)
    if(hisonConfig.domain !== undefined && hisonConfig.domain !== null) hison.setDomain(hisonConfig.domain)
    if(hisonConfig.controllerPath !== undefined && hisonConfig.controllerPath !== null) hison.setControllerPath(hisonConfig.controllerPath)
    if(hisonConfig.timeout !== undefined && hisonConfig.timeout !== null) hison.setTimeout(hisonConfig.timeout)
    if(hisonConfig.webSocketProtocol !== undefined && hisonConfig.webSocketProtocol !== null) hison.setWebSocketProtocol(hisonConfig.webSocketProtocol)
    if(hisonConfig.webSocketEndPoint !== undefined && hisonConfig.webSocketEndPoint !== null) hison.setWebSocketEndPoint(hisonConfig.webSocketEndPoint)
    if(hisonConfig.cachingLimit !== undefined && hisonConfig.cachingLimit !== null) hison.setCachingLimit(hisonConfig.cachingLimit)
    //link event
    if(hisonConfig.beforeGetRequest !== undefined && hisonConfig.beforeGetRequest !== null) hison.setBeforeGetRequest(hisonConfig.beforeGetRequest)
    if(hisonConfig.beforePostRequest !== undefined && hisonConfig.beforePostRequest !== null) hison.setBeforePostRequest(hisonConfig.beforePostRequest)
    if(hisonConfig.beforePutRequest !== undefined && hisonConfig.beforePutRequest !== null) hison.setBeforePutRequest(hisonConfig.beforePutRequest)
    if(hisonConfig.beforePatchRequest !== undefined && hisonConfig.beforePatchRequest !== null) hison.setBeforePatchRequest(hisonConfig.beforePatchRequest)
    if(hisonConfig.beforeDeleteRequest !== undefined && hisonConfig.beforeDeleteRequest !== null) hison.setBeforeDeleteRequest(hisonConfig.beforeDeleteRequest)
    if(hisonConfig.afterGetRequest !== undefined && hisonConfig.afterGetRequest !== null) hison.setAfterGetRequest(hisonConfig.afterGetRequest)
    if(hisonConfig.afterPostRequest !== undefined && hisonConfig.afterPostRequest !== null) hison.setAfterPostRequest(hisonConfig.afterPostRequest)
    if(hisonConfig.afterPutRequest !== undefined && hisonConfig.afterPutRequest !== null) hison.setAfterPutRequest(hisonConfig.afterPutRequest)
    if(hisonConfig.afterPatchRequest !== undefined && hisonConfig.afterPatchRequest !== null) hison.setAfterPatchRequest(hisonConfig.afterPatchRequest)
    if(hisonConfig.afterDeleteRequest !== undefined && hisonConfig.afterDeleteRequest !== null) hison.setAfterDeleteRequest(hisonConfig.afterDeleteRequest)
    if(hisonConfig.beforeGetUrlRequest !== undefined && hisonConfig.beforeGetUrlRequest !== null) hison.setBeforeGetUrlRequest(hisonConfig.beforeGetUrlRequest)
    if(hisonConfig.beforePostUrlRequest !== undefined && hisonConfig.beforePostUrlRequest !== null) hison.setBeforePostUrlRequest(hisonConfig.beforePostUrlRequest)
    if(hisonConfig.beforePutUrlRequest !== undefined && hisonConfig.beforePutUrlRequest !== null) hison.setBeforePutUrlRequest(hisonConfig.beforePutUrlRequest)
    if(hisonConfig.beforePatchUrlRequest !== undefined && hisonConfig.beforePatchUrlRequest !== null) hison.setBeforePatchUrlRequest(hisonConfig.beforePatchUrlRequest)
    if(hisonConfig.beforeDeleteUrlRequest !== undefined && hisonConfig.beforeDeleteUrlRequest !== null) hison.setBeforeDeleteUrlRequest(hisonConfig.beforeDeleteUrlRequest)
    if(hisonConfig.afterGetUrlRequest !== undefined && hisonConfig.afterGetUrlRequest !== null) hison.setAfterGetUrlRequest(hisonConfig.afterGetUrlRequest)
    if(hisonConfig.afterPostUrlRequest !== undefined && hisonConfig.afterPostUrlRequest !== null) hison.setAfterPostUrlRequest(hisonConfig.afterPostUrlRequest)
    if(hisonConfig.afterPutUrlRequest !== undefined && hisonConfig.afterPutUrlRequest !== null) hison.setAfterPutUrlRequest(hisonConfig.afterPutUrlRequest)
    if(hisonConfig.afterPatchUrlRequest !== undefined && hisonConfig.afterPatchUrlRequest !== null) hison.setAfterPatchUrlRequest(hisonConfig.afterPatchUrlRequest)
    if(hisonConfig.afterDeleteUrlRequest !== undefined && hisonConfig.afterDeleteUrlRequest !== null) hison.setAfterDeleteUrlRequest(hisonConfig.afterDeleteUrlRequest)
    if(hisonConfig.interceptApiResult !== undefined && hisonConfig.interceptApiResult !== null) hison.setInterceptApiResult(hisonConfig.interceptApiResult)
    if(hisonConfig.interceptApiError !== undefined && hisonConfig.interceptApiError !== null) hison.setInterceptApiError(hisonConfig.interceptApiError)
}
