import type { Hison } from 'hisonjs';
import type { HisonConfig } from '../types'

export const setHisonConfig = (hison: Hison, hisonConfig: HisonConfig) => {
    //utils
    if(hisonConfig.dateFormat) hison.setDateFormat(hisonConfig.dateFormat)
    if(hisonConfig.timeFormat) hison.setTimeFormat(hisonConfig.timeFormat)
    if(hisonConfig.datetimeFormat) hison.setDatetimeFormat(hisonConfig.datetimeFormat)
    if(hisonConfig.yearFormat) hison.setYearFormat(hisonConfig.yearFormat)
    if(hisonConfig.monthFormat) hison.setMonthFormat(hisonConfig.monthFormat)
    if(hisonConfig.yearMonthFormat) hison.setYearMonthFormat(hisonConfig.yearMonthFormat)
    if(hisonConfig.dayFormat) hison.setDayFormat(hisonConfig.dayFormat)
    if(hisonConfig.dayOfWeekFormat) hison.setDayOfWeekFormat(hisonConfig.dayOfWeekFormat)
    if(hisonConfig.hourFormat) hison.setHourFormat(hisonConfig.hourFormat)
    if(hisonConfig.hourMinuteFormat) hison.setHourMinuteFormat(hisonConfig.hourMinuteFormat)
    if(hisonConfig.minuteFormat) hison.setMinuteFormat(hisonConfig.minuteFormat)
    if(hisonConfig.secondFormat) hison.setSecondFormat(hisonConfig.secondFormat)
    if(hisonConfig.numberFormat) hison.setNumberFormat(hisonConfig.numberFormat)
    if(hisonConfig.LESSOREQ_0X7FF_BYTE) hison.setCharByteLess2047(hisonConfig.LESSOREQ_0X7FF_BYTE)
    if(hisonConfig.LESSOREQ_0XFFFF_BYTE) hison.setCharByteLess65535(hisonConfig.LESSOREQ_0XFFFF_BYTE)
    if(hisonConfig.GREATER_0XFFFF_BYTE) hison.setCharByteGreater65535(hisonConfig.GREATER_0XFFFF_BYTE)
    //shield
    if(hisonConfig.shieldURL) hison.setShieldURL(hisonConfig.shieldURL)
    if(hisonConfig.exposeIpList) hison.setExposeIpList(hisonConfig.exposeIpList)
    if(hisonConfig.isFreeze) hison.setIsFreeze(hisonConfig.isFreeze)
    if(hisonConfig.isPossibleGoBack) hison.setIsPossibleGoBack(hisonConfig.isPossibleGoBack)
    if(hisonConfig.isPossibleOpenDevTool) hison.setIsPossibleOpenDevTool(hisonConfig.isPossibleOpenDevTool)
    if(hisonConfig.doDetectDevTool) hison.setDoDetectDevTool(hisonConfig.doDetectDevTool)
    //data
    if(hisonConfig.convertValue) hison.setConvertValue(hisonConfig.convertValue)
    //link
    if(hisonConfig.protocol) hison.setProtocol(hisonConfig.protocol)
    if(hisonConfig.domain) hison.setDomain(hisonConfig.domain)
    if(hisonConfig.controllerPath) hison.setControllerPath(hisonConfig.controllerPath)
    if(hisonConfig.timeout) hison.setTimeout(hisonConfig.timeout)
    if(hisonConfig.webSocketProtocol) hison.setWebSocketProtocol(hisonConfig.webSocketProtocol)
    if(hisonConfig.webSocketEndPoint) hison.setWebSocketEndPoint(hisonConfig.webSocketEndPoint)
    if(hisonConfig.cachingLimit) hison.setCachingLimit(hisonConfig.cachingLimit)
    //link event
    if(hisonConfig.beforeGetRequest) hison.setBeforeGetRequest(hisonConfig.beforeGetRequest)
    if(hisonConfig.beforePostRequest) hison.setBeforePostRequest(hisonConfig.beforePostRequest)
    if(hisonConfig.beforePutRequest) hison.setBeforePutRequest(hisonConfig.beforePutRequest)
    if(hisonConfig.beforePatchRequest) hison.setBeforePatchRequest(hisonConfig.beforePatchRequest)
    if(hisonConfig.beforeDeleteRequest) hison.setBeforeDeleteRequest(hisonConfig.beforeDeleteRequest)
    if(hisonConfig.afterGetRequest) hison.setAfterGetRequest(hisonConfig.afterGetRequest)
    if(hisonConfig.afterPostRequest) hison.setAfterPostRequest(hisonConfig.afterPostRequest)
    if(hisonConfig.afterPutRequest) hison.setAfterPutRequest(hisonConfig.afterPutRequest)
    if(hisonConfig.afterPatchRequest) hison.setAfterPatchRequest(hisonConfig.afterPatchRequest)
    if(hisonConfig.afterDeleteRequest) hison.setAfterDeleteRequest(hisonConfig.afterDeleteRequest)
    if(hisonConfig.beforeGetUrlRequest) hison.setBeforeGetUrlRequest(hisonConfig.beforeGetUrlRequest)
    if(hisonConfig.beforePostUrlRequest) hison.setBeforePostUrlRequest(hisonConfig.beforePostUrlRequest)
    if(hisonConfig.beforePutUrlRequest) hison.setBeforePutUrlRequest(hisonConfig.beforePutUrlRequest)
    if(hisonConfig.beforePatchUrlRequest) hison.setBeforePatchUrlRequest(hisonConfig.beforePatchUrlRequest)
    if(hisonConfig.beforeDeleteUrlRequest) hison.setBeforeDeleteUrlRequest(hisonConfig.beforeDeleteUrlRequest)
    if(hisonConfig.afterGetUrlRequest) hison.setAfterGetUrlRequest(hisonConfig.afterGetUrlRequest)
    if(hisonConfig.afterPostUrlRequest) hison.setAfterPostUrlRequest(hisonConfig.afterPostUrlRequest)
    if(hisonConfig.afterPutUrlRequest) hison.setAfterPutUrlRequest(hisonConfig.afterPutUrlRequest)
    if(hisonConfig.afterPatchUrlRequest) hison.setAfterPatchUrlRequest(hisonConfig.afterPatchUrlRequest)
    if(hisonConfig.afterDeleteUrlRequest) hison.setAfterDeleteUrlRequest(hisonConfig.afterDeleteUrlRequest)
    if(hisonConfig.interceptApiResult) hison.setInterceptApiResult(hisonConfig.interceptApiResult)
    if(hisonConfig.interceptApiError) hison.setInterceptApiError(hisonConfig.interceptApiError)
}
